import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { defineConfig, type DefaultTheme } from "vitepress";

const docsRoot = path.resolve(__dirname, "..");

/** First level-one heading of a markdown file, or the file name. */
const titleOf = (file: string): string => {
  const match = /^#\s+(.+)$/m.exec(readFileSync(file, "utf8"));
  return match?.[1]?.trim() ?? path.basename(file, ".md");
};

/** Sidebar items for every markdown file directly inside `docs/<dir>`. */
const section = (dir: string): DefaultTheme.SidebarItem[] => {
  const full = path.join(docsRoot, dir);
  if (!existsSync(full)) return [];
  return readdirSync(full)
    .filter((f) => f.endsWith(".md") && f !== "index.md")
    .sort()
    .map((f) => ({ text: titleOf(path.join(full, f)), link: `/${dir}/${f.replace(/\.md$/, "")}` }));
};

/** One sidebar entry per package generated by TypeDoc (`npm run docs:api`). */
const apiSection = (): DefaultTheme.SidebarItem[] => {
  const full = path.join(docsRoot, "api", "@rpallas");
  if (!existsSync(full)) return [];
  return readdirSync(full)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const name = f.replace(/\.md$/, "");
      return { text: `@rpallas/${name}`, link: `/api/@rpallas/${name}` };
    });
};

export default defineConfig({
  title: "outcrop",
  description:
    "Lambda-first AWS CDK constructs, account baseline, runtime helpers, CLI and reusable GitHub Actions workflows with preview stacks per pull request.",
  base: process.env["DOCS_BASE"] ?? "/outcrop/",
  lastUpdated: true,
  cleanUrls: true,
  // Links that leave `docs/` point at repository files (package READMEs, actions) and are
  // only meaningful on GitHub; they are rewritten below.
  ignoreDeadLinks: [/^https?:\/\/localhost/],
  markdown: {
    config(md) {
      // JSDoc comments and package READMEs link to `../../docs/<page>.md` so they work on
      // GitHub. Rewrite those to site paths, and send other repository-relative links to
      // GitHub itself.
      const defaultLinkOpen = md.renderer.rules.link_open;
      md.renderer.rules.link_open = (tokens, idx, options, env, self) => {
        const token = tokens[idx];
        const href = token?.attrGet("href");
        if (token && href && /^(\.\/)?(\.\.\/)+/.test(href)) {
          const docsMatch = /(?:\.\.\/)+docs\/(.+?)(?:\.md)?(#.*)?$/.exec(href);
          if (docsMatch) {
            token.attrSet("href", `/${docsMatch[1] ?? ""}${docsMatch[2] ?? ""}`);
          } else {
            const repoPath = href.replace(/^(\.\/)?(\.\.\/)+/, "");
            token.attrSet("href", `https://github.com/rpallas/outcrop/blob/main/${repoPath}`);
          }
        }
        return defaultLinkOpen
          ? defaultLinkOpen(tokens, idx, options, env, self)
          : self.renderToken(tokens, idx, options);
      };
      // Inline code such as `{{resolve:ssm:...}}` or `{{service}}` must not be
      // treated as a Vue interpolation.
      const defaultRender = md.renderer.rules.code_inline;
      md.renderer.rules.code_inline = (tokens, idx, options, env, self) => {
        tokens[idx]?.attrSet("v-pre", "");
        return defaultRender
          ? defaultRender(tokens, idx, options, env, self)
          : self.renderToken(tokens, idx, options);
      };
    },
  },
  themeConfig: {
    nav: [
      { text: "Guides", link: "/guides/getting-started" },
      { text: "Constructs", link: "/constructs/" },
      { text: "API", link: "/api/" },
      { text: "GitHub", link: "https://github.com/rpallas/outcrop" },
    ],
    sidebar: [
      { text: "Guides", items: section("guides") },
      { text: "Conventions", items: section("conventions") },
      { text: "Constructs", collapsed: true, items: section("constructs") },
      { text: "Integrations", collapsed: true, items: section("integrations") },
      { text: "Security", items: section("security") },
      { text: "Decisions", collapsed: true, items: section("adr") },
      { text: "API reference", collapsed: true, items: apiSection() },
      { text: "Roadmap", link: "/roadmap" },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/rpallas/outcrop" }],
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/rpallas/outcrop/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    footer: { message: "Released under the MIT License." },
  },
});
