import { timingSafeEqual } from "node:crypto";
import type { APIGatewayRequestSimpleAuthorizerHandlerV2 } from "aws-lambda";
import { getLogger, getSecret, requireEnv } from "@rpallas/platform-cdk-runtime";

const API_KEY_HEADER = "x-api-key";

const safeEqual = (a: string, b: string): boolean => {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
};

/**
 * Simple-response Lambda authorizer comparing the `x-api-key` header with the
 * secret generated by `PlatformSecret`. API Gateway caches the decision per
 * identity source for five minutes.
 */
export const handler: APIGatewayRequestSimpleAuthorizerHandlerV2 = async (event) => {
  const provided = event.headers?.[API_KEY_HEADER] ?? event.headers?.[API_KEY_HEADER.toUpperCase()];
  if (!provided) return { isAuthorized: false };
  const expected = await getSecret(requireEnv("API_KEY_SECRET_ARN"));
  const isAuthorized = safeEqual(provided, expected);
  if (!isAuthorized) getLogger().warn("rejected request with invalid api key", { routeKey: event.routeKey });
  return { isAuthorized, context: { auth: "api-key" } };
};
